### ISSUE TITLE
Linux Support for 3DM-GX3-25

### ISSUE THREAD

**Issue by smbryan** [LORD-MicroStrain/Drivers#1]
I'm currently trying to evaluate the 3DM-GX3-25 AHRS system. However, I need it to work with a Linux system. 

Are there Linux drivers and software available?

**Comment by rwslord** [comment]
The 3DM-GX3-25 should work on Linux as-is. Have you tried it yet, and if so, are running into issues?

**Comment by smbryan** [comment]
I have it plugged in, but no way to test it. Running `lsusb` gave `Bus 001 Device 005: ID 199b:3065 MicroStrain, Inc. 3DM-GX3-25 Orientation Sensor` just fine.

**Comment by rwslord** [comment]
when it's plugged in, can you look in /dev and see if a new ttyUSB* or ttyACM* appears?

**Comment by smbryan** [comment]
Getting a `ttyACM0`.

**Comment by smbryan** [comment]
To be clear -- I had updated the original post to drivers and software.  The device looks like it's up. However, I'm missing the link to see the data coming out. 

I think what's needed is to roll my own module following the [instructions for MSCL](http://lord-microstrain.github.io/MSCL/Documentation/Getting%20Started/index.html#inertial) unless there's a simpler solution.

**Comment by rwslord** [comment]
Ok, if I'm understanding correctly, you are looking for information on getting started developing with the 3DM-GX3-25?

There are two approaches here:

1. Use MSCL, which is a high-level library that abstracts away all the low-level bytes, serial ports, etc. The link you sent is the quick start guide, and is a great step in helping you get up and running with MSCL.

2. Use the [3DM-GX3-25 Data Communications Protocol](http://files.microstrain.com/3DM-GX3-15,-25%20MIP%20Data%20Communications%20Protocol.pdf). 

More documentation on the 3DM-GX3-25 can be found on the [product page](https://www.microstrain.com/inertial/3DM-GX3-25) (although it is no longer an active product on our main website, as it is a couple generations old at this point).

**Comment by smbryan** [comment]
Perfect -- I can work with that. Thank you for the quick and thorough response (to a poorly-phrased question).

**Comment by rwslord** [comment]
haha, no worries! Happy to help 😄
