### ISSUE TITLE
Linux driver crashing.

### ISSUE THREAD

**Issue by Para148** [LORD-MicroStrain/Drivers#2]
I am using the base-200-usb on a single board linux computer with the drivers provided here: https://github.com/LORD-MicroStrain/Drivers/releases/tag/linux-cp210x-0.2

I have a python script running the MSCL library to collect data from several sg-link nodes. After 6-12 hours of the system running the driver breaks, the /dev/ttyUSB0 is replaced by a /dev/ttyUSB1 and my python script gets an end of file exception. 

Windows never gives me this error when I run my script from there. I'm not sure if its the linux drivers causing this or the arm-linux MSCL library that I compiled.

**Comment by Para148** [comment]
I've attached a kernel log of the issue. 
[log.txt](https://github.com/LORD-MicroStrain/Drivers/files/2677992/log.txt)

**Comment by rwslord** [comment]
Do you see this happen every time?

**Comment by Para148** [comment]
When I'm running with 2 nodes it happens 1/3rd of the time from a fresh boot of my single board computer as well as every 6-12 hours after a successful start.

When I'm running with 5 nodes it always happens at the start and wont ever get the the data collection part of my code. 

I tried modifying my code to load or unload the cp210x driver. This manages to successfully restart the system during the 2 node case, but it gets stuck endlessly restarting in the 5 node case. I also tried having my code make a basestation on /dev/ttyUSB1 when that happens but its basically the same result. 

People have reported similar issues for other devices using that chip too.
https://www.google.com/search?q=cp210x+ttyUSB0%3A+failed+set+request+0x7+status%3A+-19&rlz=1C1GGRV_enCA754CA754&oq=cp21&aqs=chrome.1.69i59l3j69i60l2j69i57.2736j1j7&sourceid=chrome&ie=UTF-8

**Comment by jpherbst** [comment]
Which SBC are you using?

**Comment by jpherbst** [comment]
The thing is it looks like it gets a VBUS error first which means that the voltage might be drooping due to not enough current supplied or a loose connection.  Are you successfully running your tests on Windows on the SBC or another computer.

**Comment by Para148** [comment]
I just ran the sbc with a bigger power supply and everything works now.
Thanks so much.
